name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Create directories
      run: |
        mkdir -p tests/test_plugins
        mkdir -p settings
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
    - name: Run tests
      run: |
        pytest tests/
    - name: Create necessary directories for tests
      run: |
        mkdir -p tests/test_plugins
        mkdir -p settings
        echo '{"indentation": 4, "line_length": 88, "string_quotes": "double", "trailing_commas": true}' > settings/custom_style.json